### ISSUE TITLE
Suggestion: Place a benchmark result in readme or somewhere else

### ISSUE THREAD

**Issue by ljsnogard** [ufcpp/StringLiteralGenerator#15]
That would make this performance optimization design more convincing.
Consider performance under AOT and JIT conditions would be better.

**Comment by ufcpp** [comment]
see: https://github.com/dotnet/csharplang/blob/main/proposals/utf8-string-literals.md#examples-today

This is an excuse not to provide benchmarks, but it is a widely known fact that getting UTF-8 bytes from string literals is not efficient.
