### ISSUE TITLE
Included in reference list

### ISSUE THREAD

**Issue by amis92** [ufcpp/StringLiteralGenerator#9]
Hi,

I've included your repository in my personal [C# Source Generators list](https://github.com/amis92/csharp-source-generators) to help gather these kind of projects in one place and hopefully under single umbrella, thus I propose to add the `csharp-sourcegenerator` topic to this repository to help with visibility.

I hope you're okay with this. If you happen to know other generator projects, I'll be happy to enlist those in my list as well.

Thanks!

**Comment by ufcpp** [comment]
> thus I propose to add the csharp-sourcegenerator topic

Any templates? How should I add the topic.

FYI, I have another source generator: https://github.com/ufcpp/MemberAccessGenerator

**Comment by amis92** [comment]
The topic is added via the cog beside about and shows up like that:
![image](https://user-images.githubusercontent.com/2671396/95651774-cfcfe500-0aec-11eb-9eae-0c101469a627.png)

**Comment by ufcpp** [comment]
Tanks. done.

**Comment by amis92** [comment]
> FYI, I have another source generator: https://github.com/ufcpp/MemberAccessGenerator

Also added :) Thanks!
